# -*- coding: utf-8 -*-
"""comet_gymnasium_example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/comet-ml/comet-examples/blob/master/integrations/reinforcement-learning/gymnasium/notebooks/comet_gymnasium_example.ipynb

<img src="https://cdn.comet.ml/img/notebook_logo.png">  <img height=90px align="right" src="https://raw.githubusercontent.com/Farama-Foundation/Gymnasium/main/gymnasium-text.png">

[Comet](https://www.comet.com/?utm_source=gymnasium&utm_medium=partner&utm_campaign=partner_gymnasium_2023&utm_content=comet_colab) helps accelerate machine learning through experiment tracking and production monitoring. Never lose track of your work and easily share results and collaborate across teams of all sizes.

**This notebook shows you how to log your Gymnasium metrics with Comet.** For more information about Comet's integration with Gymnasium, visit our [Docs](https://www.comet.com/docs/v2/integrations/ml-frameworks/gymnasium/?utm_source=gymnasium&utm_medium=partner&utm_campaign=partner_gymnasium_2023&utm_content=comet_colab) page.

If you prefer to preview what's to come, check out completed experiments created from this notebook [here](https://www.comet.com/examples/comet-examples-gymnasium-notebook/?utm_source=gymnasium&utm_medium=partner&utm_campaign=partner_gymnasium_2023&utm_content=comet_colab).

# Install Required Packages
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install 'gymnasium[classic-control]' comet_ml stable-baselines3

"""# Initialize Comet

Create your free account at [Comet.com](https://www.comet.com/signup?utm_source=gymnasium&utm_medium=partner&utm_campaign=partner_gymnasium_2023&utm_content=comet_colab) and grab your API key which can be found under account settings.
"""

# import comet_ml

# comet_ml.init(project_name="comet-examples-gymnasium-notebook")

"""# Train an Agent using StableBaselines3 A2C Algorithm"""

from comet_ml.integration.gymnasium import CometLogger
from stable_baselines3 import A2C
import gymnasium as gym

env = gym.make("Acrobot-v1", render_mode="rgb_array")

# Uncomment if you want to Upload Videos of your environment to Comet
# env = gym.wrappers.RecordVideo(env, 'test')





model = A2C("MlpPolicy", env, verbose=0)
model.learn(total_timesteps=10000)

env.close()


"""# Train an Agent using StableBaselines3 PPO Algorithm"""

from stable_baselines3 import PPO


env = gym.make("Acrobot-v1", render_mode="rgb_array")

# Uncomment if you want to Upload Videos of your environment to Comet
# env = gym.wrappers.RecordVideo(env, 'test')




model = PPO("MlpPolicy", env, verbose=0)
model.learn(total_timesteps=10000)

env.close()

"""# Use Comet's UI to Benchmark Different RL Algorithims"""
